# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-28 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='uri',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
